# VM Memory Layout Constants
VM_MEMORY_SIZE = 1024 * 1024
VM_DATA_SECTION_START = 0x1000
VM_CODE_SECTION_START = 0x2000
VM_STACK_START = VM_MEMORY_SIZE - 1
VM_STACK_FRAME_SIZE = 1024
VM_INTERRUPT_COUNT = 256
VM_INTERRUPT_VECTOR_START = 0

# Error Codes
VM_ERROR_NONE = 0
VM_ERROR_NULL_POINTER = 1
VM_ERROR_INVALID_MEMORY_ACCESS = 2
VM_ERROR_STACK_OVERFLOW = 3
VM_ERROR_STACK_UNDERFLOW = 4
VM_ERROR_INVALID_OPCODE = 5
VM_ERROR_DIVISION_BY_ZERO = 6
VM_ERROR_OUT_OF_MEMORY = 7
VM_ERROR_INVALID_FREE = 8

# Data Section Constants
VM_DATA_SECTION_MAGIC = 0xDA7A
VM_DATA_SECTION_ALIGN = 16